### ISSUE TITLE
[QAIT] Application does not direct user to the Ezi-pay payment page when amount in shopping cart is greater than 1000

### ISSUE THREAD

**Issue by Vishuarora-qait** [Certegy/certegy-ezipay-magento-2.x#1]
**Test Data:** This issue is reproducible on following devices:
Safari with iOS 11.1
Android 7 with Chrome 62

**Pre-requisite:**
Admin has configured the ‘Ezi-pay’ for AU region

**Steps to reproduce:**
1. Launch the site: http://ec2-13-210-68-144.ap-southeast-2.compute.amazonaws.com
2. Add products in cart (amount greater than 1000)
3. Click on ‘Proceed to Checkout’ button
4. Verify that application displays ‘Estimated Total’ as $2,370.00
5. Enter shipping address
6. Select payment method as ‘Ezi-Pay’ and click on ‘Place Order’ button
7. Verify the result

**Actual Result:** Application does not direct user to the Ezi-pay payment page when amount is greater than 1000 instead it directs user to the ‘Shopping Cart’ page.

Refer to the screen-cast <<http://screencast-o-matic.com/watch/cbXQhV2ld8>> Expected Result:

**Expected Result:** Application should direct user to the Ezi-pay payment page till the amount in shopping cart is greater than maximum value configured in admin.

**Comment by sam-flexi** [comment]
Tested and passed.
