### ISSUE TITLE
[QAIT] Ezi-Pay> ‘Your Details’ screen: Application does not allow user to make payment if user has completed 18 years today.

### ISSUE THREAD

**Issue by Vishuarora-qait** [Certegy/certegy-ezipay-magento-2.x#13]
**Test Data:** This issue is reproducible on all mobile devices and desktop.

**Pre-requisite:**
Admin has configured the ‘Ezi-pay’ for AU region

**Steps to reproduce:**
1. Launch URL: http://ec2-13-210-68-144.ap-southeast-2.compute.amazonaws.com
2. Add any product in cart and proceed to checkout using Ezi-Pay.
3. Enter phone number and verification code on subsequent screens.
4. Enter DOB in date of birth column so that user is completing 18 years today like 09/11/1999
5. Verify that application does not display any error message but screen gets refreshed instead of proceeding.

**Actual Result:** Application does not display any error message but screen gets refreshed instead of proceeding further.

Refer to screencast <<http://screencast-o-matic.com/watch/cbXQlT2IfQ >> for more details.

**Expected Result:** Application should proceed with payment if user has completed 18 years today.

**Comment by sam-flexi** [comment]
Similar issue found on WooCommerce board.
