### ISSUE TITLE
[QAIT] Ezi-Pay> ‘Your Details’ screen: Application declines payment in case user's age is going to be 90 years in 1 or 2 days

### ISSUE THREAD

**Issue by Vishuarora-qait** [Certegy/certegy-ezipay-magento-2.x#15]
**Test Data:** This issue is reproducible on all mobile devices and desktop.

**Pre-requisite:**
Admin has configured the ‘Ezi-pay’ for AU region

**Steps to reproduce:**
1. Launch URL: http://ec2-13-210-68-144.ap-southeast-2.compute.amazonaws.com
2. Add any product in cart and proceed to checkout using Ezi-Pay.
3. Enter phone number and verification code on subsequent screens.
4. Enter DOB in date of birth column so that user is going to complete 90 years in 1 or 2 days like 10/11/1927
5. Verify that application declines payment in this case

**Actual Result:** Application declines payment in case user's age is going to be 90 years in 1 or 2 days.

Refer to screencast <<http://screencast-o-matic.com/watch/cbXQlv2Ifr >> for more details.

**Expected Result:** Application should display appropriate message to user to inform him/her about 90 years age policy of Ezi-Pay

**Comment by sam-flexi** [comment]
Similar issue found on WooCommerce project.
