### ISSUE TITLE
[QAIT] Ezi-Pay> Incorrect Merchant Number or API key: Select ‘Ezi-pay’ as payment method> Cart becomes empty when user taps on browser back button from 401 error page

### ISSUE THREAD

**Issue by Vishuarora-qait** [Certegy/certegy-ezipay-magento-2.x#6]
**Test Data:** This issue is reproducible on following:
Desktop
Safari with iOS 11.1
Chrome 62 with Android 7
Samsung Internet/Android 7
Android Webview/Android 7

**Pre-requisite:**
Admin has entered the incorrect Merchant Number or API key for Ezi-Pay configuration setting

**Steps to reproduce:**
1. Launch the site: http://ec2-13-210-68-144.ap-southeast-2.compute.amazonaws.com
2. Add products in cart
3. Tap on ‘Proceed to Checkout’ button
4. Enter shipping address
5. Select payment method as ‘Ezi-Pay’ and tap on ‘Place Order’ button
6. Verify that ‘401 error’ page appears
7. Tap on browser back button to navigate back to store
8. Verify the result

**Actual Result:** Cart becomes empty when user taps on browser back button from 401 error page.

Refer to the screen-cast <<http://screencast-o-matic.com/watch/cbXQ1G2lLV >> for more details

**Expected Result:** Cart should remain active when user navigates back from 401 error page.

**Comment by Certegy** [comment]
This is unrelated to ezi-pay or the plugin. closing
