### ISSUE TITLE
 [QAIT] Magento Admin> Catalog> Products: Inventory increases with the number of items which were added in the cart of canceled/Declined transaction

### ISSUE THREAD

**Issue by Vishuarora-qait** [Certegy/certegy-ezipay-magento-2.x#9]
**Test Data:** We have verified this issue on Desktop.

**Pre-requisite:**
Admin has configured the ‘Ezi-pay’ for AU/NZ region

**Steps to reproduce:**
1. Launch the site: http://ec2-13-210-68-144.ap-southeast-2.compute.amazonaws.com
2. Add products in cart
3. Click on ‘Proceed to Checkout’ button
4. Enter shipping address
5. Select payment method as ‘Ezi-Pay’ and click on ‘Place Order’ button
6. Verify the mobile number and enter the verification code
7. Enter in 'Your details' screen and proceed further
8. Cancel the transaction from Ezi-Pay ‘Payment Method’ screen
9. Verify the inventory quantity in admin portal (Catalog> Products> Quantity)

**Actual Result:** Inventory increases with the number of items which were added in the cart of canceled/Declined transaction. 

Refer to the screencast <<http://screencast-o-matic.com/watch/cbXjlw2X7Q >> for Canceled transaction.
Refer to the screencast <<http://screencast-o-matic.com/watch/cbXQlD2IeK >> for Declined transaction.

**Expected Result:** Inventory quantity should not be updated for canceled/Declined transaction.

**Comment by Vishuarora-qait** [comment]
**Example:** We have stock of 100 in inventory.
Customer has added 5 items in shopping cart and cancelled this transaction. 
We have check the inventory again to see the stock level and observed that inventory gets increased to 105 as 100 for earlier and 5 which user has added in the cart (100+5)

**Comment by sam-flexi** [comment]
Tested and passed.

**Comment by sam-flexi** [comment]
Declined transactions increment stock by 2.
